name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '>=3.2.3 <4.0.0' # Update with your desired Flutter version

      - name: Build APK for Android
        run: flutter build apk --release --split-per-abi

      #- name: Build IPA for iOS
      #  run: |
      #    flutter build ios --no-codesign
      #    cd build/ios/iphoneos
      #    mkdir Payload
      #    cd Payload
      #    mklink /d Runner.app ../Runner.app
      #    cd ..
      #    zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "C:\\Users\\chsai\\AndroidStudioProjects\\myproject\\build\\app\\outputs\\flutter-apk\\*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
